{% set name = "semi-ate-apps-common" %}
{% set version = "1.0.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-apps-common-{{ version }}.tar.gz
  sha256: 755b1c48766fcb3905dcda5ca470bbdc5afa995fecb18e06de9217907e2f3a1f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - aiomqtt
    - python >=3.8
    - semi-ate-common
    - semi-ate-stdf

test:
  imports:
    - ate_apps_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-apps-common/
  summary: Shared helpers used by the different ate-apps, i.e. master-app, control-app, etc.)
  license: GPL-2.0-only
  license_file: ate_apps_common/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
