{% set name = "semi-ate-apps-common" %}
{% set version = "1.0.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/semi-ate-apps-common-{{ version }}.tar.gz
  sha256: ed23158f21085c690d6213310fea8df9686ca30ba9c32b4783c93ebed01e6625

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - aiomqtt
    - python >={{ python_min }}
    - semi-ate-common
    - semi-ate-stdf

test:
  imports:
    - ate_apps_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/semi-ate-apps-common/
  summary: Shared helpers used by the different ate-apps, i.e. master-app, control-app, etc.)
  license: GPL-2.0-only
  license_file: ate_apps_common/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
    - heli2src
    - Zlin526F
